CREATE GLOBAL TEMPORARY TABLE TEMP_SCRIPT_LINES ( 
	OBJECT_NAME VARCHAR2 (30) NOT NULL,
	 LINE_NO NUMBER (4) NOT NULL,
	 TEXT VARCHAR2 (4000),
	 OBJECT_TYPE VARCHAR2 (30) NOT NULL
) ON COMMIT preserve ROWS 
;